export interface Provider {
  name: string
  specialty: string
  locations: string[]
  credentials: string
  education?: string[]
  professionalInterests?: string
  personalInterests?: string
  featured?: boolean
}

export const providerSpecialties = [
  'Behavioral Health',
  'Family Medicine',
  'Internal Medicine',
  'Internal Medicine & Pediatrics',
  'Nutrition',
  'Obstetrics & Gynecology',
  'Optometry',
  'Pediatrics',
  'Preventive Medicine',
  'Psychiatry',
  'Women\'s Health',
] as const

export type ProviderSpecialty = typeof providerSpecialties[number]

export const providers: Provider[] = [
  {
    name: 'Adeline Adachi, APRN',
    specialty: 'Family Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa'],
  },
  {
    name: 'Alice Ramos-Yoshida, APRN',
    specialty: 'Pediatrics',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'Pediatric Nurse Practitioner - Board Certified',
    education: ['Hawaii Loa College', 'University of Hawaii at Manoa'],
  },
  {
    name: 'Ann Chang, MD, MPH',
    specialty: 'Obstetrics & Gynecology',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'American Board of Obstetrics & Gynecology',
    education: ['Harvard College', 'Harvard Medical School', 'University of Hawaii - Obstetrics & Gynecology', 'Master of Public Health - University of Hawaii'],
  },
  {
    name: 'Asia Ayabe, MD',
    specialty: 'Obstetrics & Gynecology',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'American Board of Obstetrics & Gynecology',
    education: ['Pomona College', 'University of Hawaii John A. Burns School of Medicine', 'University of Hawaii - Obstetrics & Gynecology'],
  },
  {
    name: 'Blandina Mamaclay, APRN',
    specialty: 'Pediatrics',
    locations: ['Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'Pediatric Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa'],
    personalInterests: 'Enjoys Bikram Yoga, walking, nature',
  },
  {
    name: 'Camille Ambrose-Santos, LCSW',
    specialty: 'Behavioral Health',
    locations: ['Downtown Family Medical & Dental — 89 S King St', 'Behavioral Health & Medical — 952 N King St'],
    credentials: 'Licensed Clinical Social Worker',
    education: ['University of Hawaii at Manoa', 'Master of Social Work'],
  },
  {
    name: 'Carmen Linhares, CNM',
    specialty: 'Women\'s Health',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'Certified Nurse-Midwife',
  },
  {
    name: 'Chen Yen Wang, APRN, PhD',
    specialty: 'Internal Medicine',
    locations: ['Downtown Family Medical & Dental — 89 S King St', 'Behavioral Health & Medical — 952 N King St'],
    credentials: 'Adult Nurse Practitioner - Board Certified',
    education: ['University of Tennessee, Knoxville', 'Ph.D. in Biochemistry - University of Tennessee, Knoxville'],
  },
  {
    name: 'Christina Ho, APRN',
    specialty: 'Internal Medicine',
    locations: ['Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa'],
  },
  {
    name: 'Darrin Sato, LCSW',
    specialty: 'Behavioral Health',
    locations: ['Downtown Family Medical & Dental — 89 S King St', 'Main Medical & Dental Center — 915 N King St'],
    credentials: 'Licensed Clinical Social Worker',
    education: ['University of Hawaii at Manoa', 'Master of Social Work'],
  },
  {
    name: 'Erean Larryfiakpuyi, LCSW',
    specialty: 'Behavioral Health',
    locations: [],
    credentials: 'Licensed Clinical Social Worker',
  },
  {
    name: 'Glenn Rediger, MD',
    specialty: 'Internal Medicine',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'American Board of Internal Medicine',
    education: ['Taylor University', 'Indiana University', 'University of Hawaii - Internal Medicine', 'Prince Leopold Institute of Tropical Medicine'],
  },
  {
    name: 'Hanh Le-Scott, APRN',
    specialty: 'Family Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa', 'Master of Business Administration - Chaminade University of Honolulu'],
  },
  {
    name: 'Jackie Hui, APRN',
    specialty: 'Family Medicine',
    locations: ['Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa'],
  },
  {
    name: 'Jermaine Turner, LCSW',
    specialty: 'Behavioral Health',
    locations: ['Behavioral Health & Medical — 952 N King St', 'Main Medical & Dental Center — 915 N King St', 'Ka\'a\'ahi Clinic — 546 Ka\'a\'ahi St'],
    credentials: 'Licensed Clinical Social Worker',
    education: ['Master of Social Work'],
  },
  {
    name: 'Jesus Lucas, MD, PhD',
    specialty: 'Family Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'American Board of Family Medicine',
    education: ['University of the Philippines College of Arts and Sciences', 'University of the Philippines College of Medicine', 'Louisiana State University Health Sciences Center-Shreveport - Family Medicine', 'Ph.D. in Physiology - Wayne State University'],
  },
  {
    name: 'Joanne Williams, APRN',
    specialty: 'Psychiatry',
    locations: ['Behavioral Health & Medical — 952 N King St'],
    credentials: 'Board Certified ANCC',
    featured: true,
    education: [
      'Saint John Fisher University — MSN, PMHNP',
      'SUNY Brockport — BSN',
      'SUNY Geneseo — BA in English',
    ],
    professionalInterests: 'Joanne is a board-certified Psychiatric-Mental Health Nurse Practitioner (PMHNP-BC) with extensive experience providing care across the lifespan. She brings strong clinical expertise in psychiatric evaluation, diagnosis, medication management, and evidence-based psychotherapy, along with advanced skills in crisis intervention and high-acuity care. Grounded in integrity and the principles of beneficence and non-maleficence, she delivers patient-centered, collaborative care. Passionate about reducing mental health stigma, she empowers patients to achieve lasting cognitive and behavioral change by fostering a safe and supportive environment that promotes growth and resilience. A diverse background in psychiatry, pediatrics, and education informs a holistic and compassionate approach to care.',
    personalInterests: 'Joanne enjoys journaling about life, reading books with meaningful and transformative insights, and spending time outdoors surfing, hiking, and swimming in the ocean. She embraces adventure and values opportunities for exploration and personal growth.',
  },
  {
    name: 'Julika Kaplan, MD',
    specialty: 'Internal Medicine & Pediatrics',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'Medical Doctor',
  },
  {
    name: 'Kaitlynn Ebisutani, MD',
    specialty: 'Obstetrics & Gynecology',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'American Board of Obstetrics & Gynecology',
    education: ['University of Washington', 'University of Hawaii John A. Burns School of Medicine', 'University of Hawaii - Obstetrics & Gynecology'],
  },
  {
    name: 'Kesha Mimms, APRN',
    specialty: 'Psychiatry',
    locations: ['Behavioral Health & Medical — 952 N King St', 'Downtown Family Medical & Dental — 89 S King St', 'Ka\'a\'ahi Clinic — 546 Ka\'a\'ahi St'],
    credentials: 'Psychiatric Mental Health Nurse Practitioner',
    education: [
      'Northeastern University',
      'Salem State University',
      'Northeast Behavioral Health / Lahey Haverhill Clinic / Cornerstone Day Program',
    ],
    professionalInterests: 'Adults, geriatrics, SUD, LGBTQ, SPMI',
    personalInterests: 'Yoga, hiking, cooking, family, and dancing',
  },
  {
    name: 'Kyle Alimurung, MD',
    specialty: 'Internal Medicine',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'American Board of Internal Medicine',
    education: ['Ateneo de Manila University', 'University of Santo Tomas', 'University of Hawaii - Internal Medicine'],
    personalInterests: 'I enjoy traveling to different parts of the world to experience new cultures and new cuisines. I love spending time with my family and friends, as well as reading comic books, playing video games, and watching movies.',
    featured: true,
  },
  {
    name: 'Leanna Gordon, DO, MPH',
    specialty: 'Preventive Medicine',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Main Medical & Dental Center — 915 N King St'],
    credentials: 'American Board of Preventive Medicine',
    education: ['Grand Valley State University', 'Michigan State University College of Osteopathic Medicine', 'Madigan Army Medical Center - Preventive Medicine', 'Master of Public Health - University of Washington'],
    professionalInterests: 'Preventive Medicine, Lifestyle Medicine',
    personalInterests: 'Hiking, Snorkeling, Reading',
  },
  {
    name: 'Lynne Saito-Tom, MD',
    specialty: 'Obstetrics & Gynecology',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'American Board of Obstetrics & Gynecology',
    education: ['Willamette University', 'University of Hawaii John A. Burns School of Medicine', 'University of Hawaii - Obstetrics & Gynecology'],
  },
  {
    name: 'Maile Ishikawa, RD',
    specialty: 'Nutrition',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'Certified Diabetes Care and Education Specialist (CDCES)',
    education: ['University of Hawaii at Manoa'],
    professionalInterests: 'Returned Peace Corps Volunteer (Youth Development Specialist) from Sept 2017-Nov 2019 in Ukraine. Hawaii Academy of Nutrition and Dietetics (HAND) Web Editor from Jun 2022-Jun 2025. 2025 Hawaii Recognized Young Dietitian of the Year.',
    personalInterests: 'Traveling, Staying physically active, Spending time with family',
    featured: true,
  },
  {
    name: 'Matthew Marchetto-Ryan, Psy.D',
    specialty: 'Behavioral Health',
    locations: ['Behavioral Health & Medical — 952 N King St', 'Main Medical & Dental Center — 915 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'Licensed Clinical Psychologist — Hawai\'i State',
    education: [
      'Hawai\'i School of Professional Psychology at Argosy University',
      'Master of Science in Psychopharmacology — Alliant University',
    ],
    professionalInterests: 'Generalist — Community Mental Health Care',
    personalInterests: 'Hiking, biking, gardening, reading (fiction), movies, and gaming',
  },
  {
    name: 'Michael Walter, MD, MPH',
    specialty: 'Pediatrics',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'American Board of Pediatrics',
    education: ['The University of North Texas', 'The University of Texas Medical Branch at Galveston', 'Austin Pediatric Education Program - Pediatrics', 'Master of Public Health - University of Hawaii'],
  },
  {
    name: 'Milani Kyaw, APRN',
    specialty: 'Women\'s Health',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'Women\'s Health Nurse Practitioner - Board Certified',
    education: ['Saint Mary\'s College of California', 'Vanderbilt University'],
    professionalInterests: 'Preconception and prenatal care, sexual health education, family planning',
    personalInterests: 'Pilates, hiking, beach sunsets, cooking shows',
  },
  {
    name: 'Mish Kuklok, APRN',
    specialty: 'Family Medicine',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa'],
  },
  {
    name: 'Nafanua Braginsky, APRN',
    specialty: 'Family Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Hawaii at Manoa'],
    professionalInterests: 'Community Outreach',
    personalInterests: 'A day to sleep without disruption',
  },
  {
    name: 'Naoko Hokari, MD',
    specialty: 'Pediatrics',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'American Board of Pediatrics',
    education: ['Columbia University', 'Mount Sinai School of Medicine', 'Robert Wood Johnson Medical School - Pediatrics'],
  },
  {
    name: 'Narelie Domingo Calley, APRN',
    specialty: 'Family Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['University of Phoenix', 'University of Hawaii at Manoa'],
  },
  {
    name: 'Ricardo Molero Bravo, MD',
    specialty: 'Obstetrics & Gynecology',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'American Board of Obstetrics & Gynecology',
    education: ['University of South Florida', 'University of Central Florida, College of Medicine', 'University of Hawaii - Obstetrics & Gynecology'],
  },
  {
    name: 'Richard Ricardo, MD',
    specialty: 'Pediatrics',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'American Board of Pediatrics',
    education: ['University of California, Los Angeles', 'University of Hawaii John A. Burns School of Medicine', 'University of Hawaii - Pediatrics'],
  },
  {
    name: 'Rieko Nieto, LCSW',
    specialty: 'Behavioral Health',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Behavioral Health & Medical — 952 N King St'],
    credentials: 'Licensed Clinical Social Worker / Certified Substance Abuse Counselor',
    education: ['University of Hawaii at Manoa', 'Master of Social Work'],
    personalInterests: 'Tahitian dance, hula, surfing, hiking, and fishing',
  },
  {
    name: 'Ritabelle Fernandes, MD, MPH',
    specialty: 'Internal Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St', 'Ka\'a\'ahi Clinic — 546 Ka\'a\'ahi St'],
    credentials: 'American Board of Internal Medicine - Internal Medicine, Geriatric Medicine, Hospice & Palliative Medicine',
    education: ['D. G. Ruparel College', 'Seth G. S. Medical College', 'St. Mary\'s Hospital - Internal Medicine', 'University of Hawaii - Geriatrics', 'Master of Public Health - University of Hawaii'],
    professionalInterests: 'Dementia, Geriatric Medicine',
    personalInterests: 'Music and Arts',
  },
  {
    name: 'Stephanie Koh, APRN, MPH',
    specialty: 'Family Medicine',
    locations: ['Behavioral Health & Medical — 952 N King St'],
    credentials: 'Family Nurse Practitioner - Board Certified',
    education: ['Boston College', 'Emory University', 'Master of Public Health - Emory University'],
    professionalInterests: 'Culturally sensitive chronic disease management, diabetes prevention and management',
    personalInterests: 'Hiking, camping, crocheting, chasing my 2 rambunctious toddlers around',
  },
  {
    name: 'Steven Nishi, MD',
    specialty: 'Obstetrics & Gynecology',
    locations: ['Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'American Board of Obstetrics & Gynecology',
    education: ['University of Hawaii at Manoa', 'University of Hawaii John A. Burns School of Medicine', 'University of Hawaii - Obstetrics & Gynecology'],
  },
  {
    name: 'Susan Sims, CNM',
    specialty: 'Women\'s Health',
    locations: ['Comprehensive Primary Health Care — 710 N King St', 'Downtown Family Medical & Dental — 89 S King St'],
    credentials: 'Certified Nurse-Midwife',
    education: ['University of Missouri', 'Frontier School of Midwifery and Family Nursing'],
  },
  {
    name: 'Tracey Yamamoto-Kubo, OD',
    specialty: 'Optometry',
    locations: ['Optometry — 915 N King St'],
    credentials: 'Doctor of Optometry',
    education: ['University of Hawaii at Manoa', 'Pacific University College of Optometry'],
    professionalInterests: 'Primary Eye Care',
  },
  {
    name: 'Victor Inada, MD',
    specialty: 'Family Medicine',
    locations: ['Main Medical & Dental Center — 915 N King St'],
    credentials: 'American Board of Family Medicine',
    education: ['Massachusetts Institute of Technology', 'University of Hawaii John A. Burns School of Medicine', 'Montefiore Medical Center - Family Medicine', 'MA Psychology - UC San Diego'],
  },
  {
    name: 'Wen-Chun Yang, OD',
    specialty: 'Optometry',
    locations: ['Optometry — 915 N King St', 'Main Medical & Dental Center — 915 N King St'],
    credentials: 'Doctor of Optometry',
    education: ['University of Hawaii at Manoa', 'Inter-American University of Puerto Rico'],
  },
  {
    name: 'Yitong Ma, MD',
    specialty: 'Pediatrics',
    locations: ['Downtown Family Medical & Dental — 89 S King St', 'Comprehensive Primary Health Care — 710 N King St'],
    credentials: 'American Board of Pediatrics',
    education: ['Creighton University', 'Creighton University School of Medicine', 'Texas Tech University Health Sciences Center - Pediatrics'],
    professionalInterests: 'General Pediatrics',
    personalInterests: 'Cats and kittens',
  },
]
